#!/usr/bin/python
import PyTango
import sys
from pprint import pprint
from albaemlib import AlbaEm

db = PyTango.Database()

fileDictEmOffset = "fDictEmOffset.dat"
fileDictEmOffset_all ="fDictEmOffset_Corr.dat"

def getAlbaEmIps():
    albaem_servers = db.get_server_list('PyAlbaEm*')
    albaem_devices = []
    i=0
    #find index of Server Name:
    for e in albaem_servers.value_string:
        if e == 'PyAlbaEm':
            break
        i+=1
    for s in albaem_servers:
        albaem_devices.append(db.get_device_class_list(s).value_string[i-1])
    albaem_ips = []
    for d in albaem_devices:
        albaem_ips.append(db.get_device_property(d,'AlbaEmName')['AlbaEmName'][0])
    return albaem_ips

def rangeComparator(a, b):
    a_range_unit_factor = a[-2]
    b_range_unit_factor = b[-2]
    a_range_value = a[:-2]
    b_range_value = b[:-2]
    result = -1
    if a_range_unit_factor == b_range_unit_factor:
      if a_range_value > b_range_value:
        result = 1
      elif a_range_value == b_range_value:
        result = 0
    elif a_range_unit_factor == 'm' or b_range_unit_factor == 'p':
      result = 1
    elif a_range_unit_factor == 'u' and b_range_unit_factor != 'm':
      result = 1
    elif a_range_unit_factor == 'n' and not b_range_unit_factor in ('m', 'u'):
      result = 1
    return result
    
def getOffsets(albaem_ip):
    print('\nAlbaEM: %s' % albaem_ip)
    try:
        albaem = AlbaEm(albaem_ip)
        offset_all = albaem.getOffsetsAll()
        offsetcorr_all = albaem.getOffsetCorrAll()
        print('\nACTUAL OFFSETS: ')
        pprint(repr(offset_all)) 
        dictEmOffset[albaem_ip] = offset_all      
        print('\nACTUAL OFFSETCORR: ')
        k = offsetcorr_all.keys()
        k.sort(rangeComparator)
        
        rTotal = {}
        for t  in k:
            rTotal[t]= offsetcorr_all.get(t)

        dictEmOffsetCorr[albaem_ip] = rTotal
        pprint(rTotal)
    except:
        print("Not able to retrive offset values, please check if AlbaEm is reachable...")

def writeFile():
    fDictEmOffset = open (fileDictEmOffset, "w")
    fDictEmOffset.write(dictEmOffset.__str__())
    fDictEmOffset.close()

    fDictEmOffset = open (fileDictEmOffset_all, "w")
    fDictEmOffset.write(dictEmOffsetCorr.__str__())
    fDictEmOffset.close()

    print ("\nBackup Offsets Saved on Files   ./ " + fileDictEmOffset_all + " and " + fileDictEmOffset+"\n")



if __name__ == '__main__':
    
    albaem_ips = getAlbaEmIps()
    dictEmOffsetCorr = {}
    dictEmOffset = {}
    if len(sys.argv) >= 2:
          fileDictEmOffset = sys.argv[1]
          fileDictEmOffset_all = "Corr_"+sys.argv[1]        
          target=0
          if len(sys.argv) >= 3:
              target = sys.argv[2]
              print "\nBackup to : " + target + " Device."

              for albaem_ip in albaem_ips:
                  if albaem_ip == target:
                      getOffsets(albaem_ip)
              writeFile()
          else:
              print "\nSe va a realizar Backup de todos los dispositivos."
              albaem_ips = getAlbaEmIps()
              dictEmOffsetCorr = {}
              dictEmOffset = {}
              for albaem_ip in albaem_ips:
                  getOffsets(albaem_ip)
              writeFile()
    else:
         print "\nEs necesario el nombre de fichero."
        

    

    
